version: "3.8"

services:
  nginx:
    container_name: book_exchange-nginx
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - "8080:80"
    networks:
      - book_exchange_network

  app:
    container_name: book_exchange-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/app
    depends_on:
      - db
    networks:
      - book_exchange_network

  db:
    container_name: book_exchange-db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - book_exchange_network

  node:
    container_name: node
    image: node:16-alpine
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - book_exchange_network

  artisan:
    container_name: artisan
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/app
    entrypoint: ['php', '/var/www/app/artisan']

volumes:
  postgres-data:
    driver: local
networks:
  book_exchange_network:
    driver: bridge
